name: faes-build

on:
  # build on all PRs, but only trigger push builds on `faes-jan2022`
  pull_request:
  push:
    branches:
      - faes-jan2022

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: lint
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JSCPD: false
        DEFAULT_BRANCH: faes-jan2022

  doc-build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: install latest QIIME 2 core distro (staging)
      run: |
        envFile=qiime2-latest-py38-linux-conda.yml
        wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/$envFile
        conda env create -q -p ./test-env --file $envFile

    - name: install dependencies
      run: |
        conda install -p ./test-env -q -y \
          -c conda-forge \
          -c bioconda \
          -c defaults \
          --override-channels pip

    - name: install pip dependencies
      shell: bash -l {0}
      run: |
        conda activate ./test-env
        pip install -r book/requirements.txt

    - name: build book preview
      shell: bash -l {0}
      run: |
        conda activate ./test-env
        make build_preview

    - name: build full book
      shell: bash -l {0}
      env:
        Q2DOC_HTML_BASEURL: https://qiime2-workshops.s3.us-west-2.amazonaws.com/faes-jan2022/
      run: |
        conda activate ./test-env
        make build_full

    - name: deploy to s3
      uses: jakejarvis/s3-sync-action@master
      if: ${{ github.ref == 'refs/heads/faes-jan2022' }}
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: qiime2-workshops
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'book/_build/html'
        DEST_DIR: 'faes-jan2022'
